// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKCLhk2PaFSre73MK982mpRR2NSBKh7c',
    appId: '1:886283837894:web:df3d037f6bbdd8686d12c7',
    messagingSenderId: '886283837894',
    projectId: 'ai-quran-exam',
    authDomain: 'ai-quran-exam.firebaseapp.com',
    storageBucket: 'ai-quran-exam.firebasestorage.app',
    measurementId: 'G-777RX7WV55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOsJjD2vLlJBykNdpGpD4RqOXZckdZwEk',
    appId: '1:886283837894:android:b898fe002d416a626d12c7',
    messagingSenderId: '886283837894',
    projectId: 'ai-quran-exam',
    storageBucket: 'ai-quran-exam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh9GNf8E2WPQalQa-ULSy_caIgDz5TXn4',
    appId: '1:886283837894:ios:fa96d265ab1e6e976d12c7',
    messagingSenderId: '886283837894',
    projectId: 'ai-quran-exam',
    storageBucket: 'ai-quran-exam.firebasestorage.app',
    iosBundleId: 'com.example.quranTajweedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh9GNf8E2WPQalQa-ULSy_caIgDz5TXn4',
    appId: '1:886283837894:ios:fa96d265ab1e6e976d12c7',
    messagingSenderId: '886283837894',
    projectId: 'ai-quran-exam',
    storageBucket: 'ai-quran-exam.firebasestorage.app',
    iosBundleId: 'com.example.quranTajweedApp',
  );
}
